#!/usr/bin/env bash
# SENSEI station bootstrap — idempotent setup for M1 / M2 / M3.
#
# Usage:
#   ./setup/bootstrap.sh <M1|M2|M3> [--m3-url http://host:8000]
#
# Behavior:
#   - Verifies Python >= 3.9.
#   - Creates/refreshes ./venv.
#   - Installs sensei_client from the v0.3.0 tag (public repo).
#   - Writes ./.env with SENSEI_API_URL, SENSEI_STATION, SENSEI_ADAPTER_SPEC.
#   - Runs tests/e2e_smoke.py at the end to verify wiring (requires M3 reachable).
#
# Exit codes:
#   0  everything bootstrapped + smoke test passed
#   1  smoke test failed (setup is fine, M3 not reachable or misconfigured)
#   2  bootstrap itself failed (Python version, pip install, etc.)

set -euo pipefail

# --- Argument parsing ---------------------------------------------------------
STATION="${1:-}"
M3_URL=""
shift || true

while [[ $# -gt 0 ]]; do
  case "$1" in
    --m3-url) M3_URL="${2:-}"; shift 2 ;;
    *) echo "[ERR] unknown arg: $1" >&2; exit 2 ;;
  esac
done

if [[ ! "$STATION" =~ ^(M1|M2|M3)$ ]]; then
  echo "Usage: $0 <M1|M2|M3> [--m3-url http://host:8000]" >&2
  exit 2
fi

# --- Resolve repo root (script may be called from anywhere) -------------------
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

echo "[bootstrap] station=$STATION repo_root=$REPO_ROOT"

# --- 1. Python version gate ---------------------------------------------------
PY="${PYTHON:-python3}"
if ! command -v "$PY" >/dev/null 2>&1; then
  echo "[ERR] python3 not found on PATH. Set PYTHON=... or install Python 3.9+." >&2
  exit 2
fi

PY_VER="$("$PY" -c 'import sys; print(".".join(map(str, sys.version_info[:2])))')"
PY_MAJOR="$(echo "$PY_VER" | cut -d. -f1)"
PY_MINOR="$(echo "$PY_VER" | cut -d. -f2)"
if [[ "$PY_MAJOR" -lt 3 ]] || { [[ "$PY_MAJOR" -eq 3 ]] && [[ "$PY_MINOR" -lt 9 ]]; }; then
  echo "[ERR] sensei_client requires Python >= 3.9 (found $PY_VER)" >&2
  exit 2
fi
echo "[bootstrap] Python $PY_VER  OK"

# --- 2. Resolve SENSEI_API_URL ------------------------------------------------
if [[ "$STATION" == "M3" ]]; then
  # M3 runs the SENSEI service locally.
  SENSEI_API_URL="${M3_URL:-http://localhost:8000}"
else
  # M1/M2 connect to M3. Require the URL.
  if [[ -z "$M3_URL" ]]; then
    if [[ -n "${SENSEI_API_URL:-}" ]]; then
      M3_URL="$SENSEI_API_URL"
    else
      read -rp "[bootstrap] M3 reachable URL (e.g. http://10.0.0.3:8000): " M3_URL
    fi
  fi
  if [[ -z "$M3_URL" ]]; then
    echo "[ERR] $STATION requires --m3-url or SENSEI_API_URL env var." >&2
    exit 2
  fi
  SENSEI_API_URL="$M3_URL"
fi
echo "[bootstrap] SENSEI_API_URL=$SENSEI_API_URL"

# --- 3. venv ------------------------------------------------------------------
if [[ ! -d "venv" ]]; then
  echo "[bootstrap] creating venv..."
  "$PY" -m venv venv
else
  echo "[bootstrap] venv exists, reusing"
fi
# shellcheck disable=SC1091
source venv/bin/activate
pip install --quiet --upgrade pip

# --- 4. Install sensei_client -------------------------------------------------
# M1 has the source tree locally; install editable from the working copy.
# M2/M3 pull from the public git tag.
if [[ "$STATION" == "M1" ]]; then
  echo "[bootstrap] installing sensei_client editable from local tree..."
  pip install --quiet -e .
else
  echo "[bootstrap] installing sensei_client v0.3.0 from GitHub..."
  pip install --quiet "git+https://github.com/pinz-byte/sensei-client.git@v0.3.0"
fi

INSTALLED_VER="$(python -c 'import sensei_client; print(sensei_client.__version__)')"
echo "[bootstrap] sensei_client $INSTALLED_VER installed"

# --- 5. Resolve default adapter spec path -------------------------------------
# Each station defaults to the HERALD spec for smoke-testing. Ventures
# override by setting SENSEI_ADAPTER_SPEC before check_and_escalate.
ADAPTER_SPEC="$REPO_ROOT/sensei_adapters/herald/herald.v1.json"
if [[ ! -f "$ADAPTER_SPEC" ]]; then
  echo "[WARN] $ADAPTER_SPEC not found; leave SENSEI_ADAPTER_SPEC unset" >&2
  ADAPTER_SPEC=""
fi

# --- 6. Write .env ------------------------------------------------------------
cat > .env <<EOF
# Generated by setup/bootstrap.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
# Source with:  set -a; source .env; set +a
SENSEI_STATION=$STATION
SENSEI_API_URL=$SENSEI_API_URL
SENSEI_ADAPTER_SPEC=$ADAPTER_SPEC
PYTHONPATH=$REPO_ROOT
EOF
echo "[bootstrap] wrote .env"

# --- 7. Smoke test ------------------------------------------------------------
echo "[bootstrap] running smoke test against $SENSEI_API_URL..."
set +e
SENSEI_API_URL="$SENSEI_API_URL" \
SENSEI_ADAPTER_SPEC="$ADAPTER_SPEC" \
  python tests/e2e_smoke.py
SMOKE_EXIT=$?
set -e

echo
if [[ $SMOKE_EXIT -eq 0 ]]; then
  echo "[bootstrap] DONE. Station $STATION is wired and verified."
  exit 0
elif [[ $SMOKE_EXIT -eq 1 ]]; then
  echo "[bootstrap] Setup complete, but smoke test did not fully pass."
  echo "           Check SENSEI_API_URL reachability: curl -f \"$SENSEI_API_URL/adapters\""
  exit 1
else
  echo "[bootstrap] Smoke test harness errored (exit $SMOKE_EXIT). See above." >&2
  exit 1
fi
